spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://mosfik:on1odnUunIcSgZid@cluster-alpha.dbd5m.mongodb.net/product-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka